spring:
  application:
    name: redis
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  datasource:
#    url: jdbc:postgresql://localhost:5433/data
#    username: killreal777
#    password: qwerty12345
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#server:
#  port: 8080
